### ISSUE TITLE
correções de estruturação dos requisito Funcionais

### ISSUE THREAD

**Issue by FauseSkyWalker** [mdsreq-fga-unb/2024.1-CalorieExplorer#14]
Melhorar a estrutura dos seguintes requisitos 

- [x] 1.Backlog do produto, requisito nº 5: "O sistema deve garantir que o estilo do site esteja alinhado com a identidade visual do local de trabalho do gerente." Este requisito é muito vago e carece de especificações detalhadas, tornando difícil a sua testabilidade. É necessário fornecer mais detalhes para que o desenvolvimento e a validação sejam possíveis.

- [x] 2.Backlog do produto, requisito nº 6: "O sistema deve incluir pelo menos 5 alimentos em cada categoria (proteína, carboidrato, lipídio, etc.)." Qual é a finalidade desse requisito? Quem será responsável por inserir esses 5 alimentos em cada categoria?

- [x] 3.Backlog do produto, requisito nº 7: "O sistema deve ser intuitivo e fácil de usar, com uma interface limpa e de fácil entendimento." Este requisito é muito vago. O que significa ser "intuitivo" e "fácil de usar"? Estas definições são subjetivas e precisam ser melhor especificadas para garantir que o requisito seja implementado corretamente.

**Comment by Filipe-002** [comment]
| ID   | RequisitoF uncional                                                                                                                                         |
|------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|
| RF01 | O sistema deve permitir que o gerente visualize a quantidade de calorias dos alimentos por 100g e ajuste as dietas dos clientes.                            |
| RF02 | O sistema deve permitir que o cliente visualize os alimentos incluídos em sua dieta e substitua-os por outras opções, se desejado.                          |
| RF03 | O sistema deve permitir que o gerente agende e altere horários de consultas, com uma agenda para gerenciar esses compromissos.                              |
| RF04 | O sistema deve permitir que o cliente veja o horário de suas consultas, receba notificações sobre mudanças e seja lembrado antes da consulta.               |
| RF05 | O sistema deve seguir um padrão de estilo que seja conduzente com os padrões de mercado, seguindo uma estética minimalista e agradável de utilizar.         |
| RF06 | O sistema deve possuir uma interface com cada função sendo descrita de forma clara, de forma que não polua o visual e com padrões já utilizados no mercado. |
| RF07 | O sistema deve exigir CPF, nome completo, idade, gênero, email, peso e altura para o cadastro.                                                              |
| RF08 | O sistema deve ter uma página de login separada para o gerente, distinta do login dos pacientes.                                                            |

**Comment by Filipe-002** [comment]
requisitos atualizados!
